### ISSUE TITLE
viu support

### ISSUE THREAD

**Issue by TheBearodactyl** [endaaman/tym#103]
Would it at all be possible to implement support for viu?

**Comment by TorchedSammy** [comment]
viu is what has to support tym, so i recommend opening an issue there instead. even so, vte already supports sixel so you can build tym with a sixel enabled vte

**Comment by TheBearodactyl** [comment]
oki

**Comment by endaaman** [comment]
I hope viu supports VTE.

**Comment by TheBearodactyl** [comment]
just realized I never closed the issue. Sorry about that lol
