### ISSUE TITLE
Option/argument for Window Class and Icon

### ISSUE THREAD

**Issue by r3lgar** [endaaman/tym#11]
It would be great to have something like `--icon` and `--class`, when starting with custom (non-shell) application.

#12

**Comment by endaaman** [comment]
Supported by 30dff899068c182985036e0c654fd3d5e5c46bf0

If you need custom icon used when `-e` provided, just also provide `--c:icon=hoge`. Does this meet your requirements?

**Comment by r3lgar** [comment]
Great, thanks!

**Comment by r3lgar** [comment]
Sigh…

>`gtk_window_set_wmclass` has been [deprecated](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass) since version 3.22 and should not be used in newly-written code.

But it's very useful when [starting terminal with some TUI application](12).

Shame on you, GNOME!

**Comment by r3lgar** [comment]
>So you want an option for `gtk_window_set_role()` instead?

Yes. Since `gtk_window_set_wmclass()` was marked as obsolete, this is the only way.

**Comment by endaaman** [comment]
Now I added role option in 778ab318808a8992f31906b7fe5f1a5c793cd146

**Comment by r3lgar** [comment]
Thanks. From now, `tym` can replace any terminal emulator. ^_^
