### ISSUE TITLE
Hide mouse cursor

### ISSUE THREAD

**Issue by r3lgar** [endaaman/tym#17]
(on keypress or on timeout?)

It is necessary in those cases when you read or write text. If user use `focus follows mouse`, it is very useful.

**Comment by endaaman** [comment]
What should we implement about this on `tym`?

**Comment by r3lgar** [comment]
I don't know what exactly I need to look for (I'm not familiar with GTK+/Xorg, sorry), so I didn't find anything useful.

When mouse cursor is above the input field and you start typing text in this field, GTK+ (or Xserver?) hides mouse cursor. Some terminal emulators hides mouse cursor by timeout when cursor is above the window.

**Comment by r3lgar** [comment]
Nice. Thank you.
