### ISSUE TITLE
Prompt being distordered with bash

### ISSUE THREAD

**Issue by endaaman** [endaaman/tym#18]
![screenshot at 2018-07-28 22-55-37](https://user-images.githubusercontent.com/2020942/43357863-f1c6f652-92c2-11e8-85ef-a842f7f13e41.png)

**Comment by r3lgar** [comment]
How to reproduce?

**Comment by endaaman** [comment]
no idea

**Comment by r3lgar** [comment]
I noticed that `tym` doesn't set the `$TERM` variable (it is `linux` by default) which is why many things don't work properly.

**Comment by endaaman** [comment]
That's it! Now I have added `term` option at 4f16c906e4800fddc409b478ddb0a37606559f3d and solved this problem.

Thanks!
