### ISSUE TITLE
Highlight mail address

### ISSUE THREAD

**Issue by iTakeshi** [endaaman/tym#45]
#44 (will) make URL-like strings (i.e. IRI) highlighted, however IRI includes only `mailto:foo@example.com` style mail link, since IRI necessarily requires `SCHEME:` part at the beginning of target strings.
We should support simple `foo@example.com` style, and another regex has to be defined based on [RFC6068](http://www.faqs.org/rfcs/rfc6068.html).

**Comment by endaaman** [comment]
done
