### ISSUE TITLE
Automatic copy of selection?

### ISSUE THREAD

**Issue by vstath** [endaaman/tym#49]
Hello,

Is it somehow possible to perform automatic copy to clipboard when I select text on the terminal via my mouse?

Is this a terminal feature or totally unrelated? If it's the former, then this might be a very good addition to this software.

**Comment by endaaman** [comment]
If you said that
1. when we select chars on screen the, the selected string should be stored in "PRIMARY" clipboard,
  → then it is already implemented.
2. the selected string can be stored in "CLIPBOARD" clipboard,
  → then it is not implemented and should be one of options.
3. when we click middle mouse button, the string which is stored in the "PRIMARY" clipboard should be inserted,
  → then it is already issued at #43

Which one?

**Comment by vstath** [comment]
I wasn't aware of primary vs clipboard clipboards. Middle mouse works for me. I was referring the selected string to be stored in the normal clipboard ctrl-c/ctrl-v type of ;-)

Also might be nice to have right mouse click to do the "CLIPBOARD" paste like it works with some other terminals (putty etc). Perhaps those should be configurable to enable/disable.

**Comment by endaaman** [comment]
At current HEAD of master branch, you can write like the following.

```lua
local tym = require('tym')

tym.set_hooks({
  selected = function(text)
    tym.copy(text)
  end,
  clicked = function(button)
    if button == 3 then
      tym.paste()
    end
  end
})
```

The callback `selected` is performed when some text is selected.  The API `tym.copy(text)` will save `text` to your OS clipboard.

And the callback `clicked` is performed when the mouse button is clicked. If the button is right button, the `button` value will be `3`, so when the value equals `3`,  do `tym.paste()`.

**Comment by vstath** [comment]
Works like a charm. You are very helpful. I can't thank you enough :-)

Is there an option already to trap "button 3" AND "<Shift> down"? Just out of curiosity of the options available.

**Comment by vstath** [comment]
To answer my own question: 

Must use tym.check_mod_state('<Shift>') to know if Shift is pressed.

**Comment by endaaman** [comment]
> Is there an option already to trap "button 3" AND " down"? Just out of curiosity of the options available.

> Must use tym.check_mod_state('<Shift>') to know if Shift is pressed.

`tym.check_mod_state(acc)` can check the state of mod keys but can not that of mouse buttons. So, `tym.check_button_state(button)` is needed, isn't it?

**Comment by endaaman** [comment]
It should be another issue about `tym.check_button_state()`. So closes this.
