### ISSUE TITLE
Change window title?

### ISSUE THREAD

**Issue by vstath** [endaaman/tym#53]
Hello, 

not sure if this is covered somewhere and I'm missing it. How can I change the tym window title after it's been invoked? I know how to change it at startup time but how can I do it from within the terminal itself?

**Comment by endaaman** [comment]
see https://askubuntu.com/questions/636944/how-to-change-the-title-of-the-current-terminal-tab-using-only-the-command-line . or google with `change terminal title shell` .

When a terminal title changing sequence is sent, hook `title` is performed.

On current latest **release**(v.2.3.0), return new title in hook call back and the result value will be new terminal title.

```lua
local tym = require('tym')

tym.set_hook('title', function(title)
 return 'New title is: ' .. title
end)
```

If you want to change by custom key map, you can write like the following.

```lua
local tym = require('tym')

tym.set_keymap('<Ctrl>w', function()
  tym.set('title', 'NEW TITLE')
  tym.apply()
end)
```

---

On current **master HEAD** (API has been renewed. It will be version 3.0.0),  execute `tym.set('title', new_title)` in hook call back.


```lua
local tym = require('tym')

tym.set_hook('title', function(title)
  tym.set('title', 'New title is: ' .. title)
end)
```
If you want to change by custom key map on the HEAD version,

```lua
local tym = require('tym')

tym.set_keymap('<Ctrl>w', function()
  tym.set('title', 'NEW TITLE')
end)
```

`tym.apply()` is not needed. Executing `tym.set()` and the value will be applied to the app immediately.

**Comment by vstath** [comment]
Excellent. Thank you very much for your reply. I had already tried from the link you provided without success before creating the ticket. Finally, after your reply, this worked for my bash shell:

Run tym, then:

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

and then 

echo -en "\033]0;New terminal title ABCDEF\a"

So without setting PS1 on the tym session the echo wouldn't work. I'm no shell expert, perhaps that's normal. The PS1 is from my .bashrc for my distro.

I compiled and run latest master HEAD.

**Comment by vstath** [comment]
In master HEAD, should `return false` keep the previous title?

Because it still changes the title regardless whether I `return true` or `return false`.

**Comment by endaaman** [comment]
`echo -en "\033]0;New terminal title ABCDEF\a"` does not works correctly in bash, but does in zsh. I have no idea more than this. Anyway, tym works correctly.

When `return true`, the default action(= changing title) should be canceled. So, if you write like the following,

```lua
tym.set_hook('title', function(title)
  return true
end)
```

then the title never changes (I checked this  at HEAD aafcb4d6b8ea65a90e12876076d17cf691b1df59).

**Comment by vstath** [comment]
My bad. I read your comment wrong. 

You mention that `return true` **cancels** the update. I thought the opposite. 

Works fine. Sorry for that. I misread your example :-/
