### ISSUE TITLE
[BUG] color_0 used as the background color

### ISSUE THREAD

**Issue by iTakeshi** [endaaman/tym#57]
Sometimes when I open new tym windows the background color is not set by `color_background` but `color_0` is used.

### Env info and tym version
* Arch linux x86
* tym v3.0.0, installed via AUR

### Minimum configs for reproduction
~/.config/tym/config.lua
```lua
-- empty
```

~/.config/tym/theme.lua
```lua
return {
    color_background = "#00ff00",
    color_0 = "#ff0000"
}
```

### Expected behavior
I see a green (`color_background`) background EVERY TIME I open a new tym window.

### Actual behavior
I see a red (`color_0`) background at around 80% of probability. I see a green background (correct behavior) for the remaining 20%.

### Severity
Low-to-moderate. There is a work-around solution that I can temporarily fix the background color by reloading configs with Ctrl-Shift-R.

**Comment by endaaman** [comment]
VTE does not fundamentally distinguish between `color_background` and `color_0`.  They are same. When set `color_0` ... `color_15`, tym internally uses `vte_terminal_set_colors()`, whose [doc](https://developer.gnome.org/vte/unstable/VteTerminal.html#vte-terminal-set-colors) states:

> If foreground is NULL and palette_size is greater than 0, the new foreground color is taken from palette [7]. If background is NULL and palette_size is greater than 0, the new background color is taken from palette [0].

`color_0` is applied to background color and `color_7`  is applied to foreground color. So actually, for the minimum setting, you don't need to set `color_background` and `color_foreground`.

**Comment by endaaman** [comment]
At 83f9e8b7cd309e089ad578a26497ae77133d9df9, reading order of color fields is fixed.  `color_background` , `color_foreground`, etc. always take precedence over `color_0` .. `color_15`.

**Comment by iTakeshi** [comment]
Thank you for the fix!
