### ISSUE TITLE
[RFC] Narrowing URI regex to commonly used formats

### ISSUE THREAD

**Issue by iTakeshi** [endaaman/tym#60]
Currently, `include/regex.h` accepts any valid URI string defined by [RFC3987](https://tools.ietf.org/html/rfc3987).
However, implementing the entire specification in the RFC3987 makes tym match a lot of unmeaningful string like `foo:bar` as URIs (note: `foo` as scheme name, `bar` as locator, in this case).

I'd like to discuss the following points:
1. Should we accept IPv6 format? IPv6 accepts strings in various formats like `2001:0db8::0001` or `::1` as IP addresses. This makes it difficult to distinguish a colon following scheme (`http:`) from ipv6 colons. Accepting only IPv4 would make things much easier.
2. Should we follow RFC3987 ("internationalized" URI including UTF8 chars) or just RFC3986 (ascii character only)?
3. Should we restrict type of scheme to common ones like `http`, `ftp`, or `file`? If so, which scheme should we accept?

ref: a seemingly-abandoned [`feature/highlight-uri`](https://github.com/endaaman/tym/tree/feature/highlight-uri) branch (created by the repo owner) limits the type of URI scheme like those.
https://github.com/endaaman/tym/blob/a79a2cc7be112899959939d08f00b046d2141b27/src/regex.h#L61

related issues: #45, #46 

---
Edit 2020/06/07
Checklist for solving this issue, according to the discussion below:
- [x] retain IPv6 support
    - already implemented
- [x] disallow URI without protocol like `192.168.0.1/index.html`
    - already implemented
- [x] drop non-ascii character support 
    - PR #63 
- [x] enable users to configure which URI protocols are clickable
    - PR #64

**Comment by endaaman** [comment]
Indeed, the current rules are a bit too loose. My opinion is

1. Only strings containing protocol  should be clickable.
2. It doesn't matter whether the internationalized URI should be clickable or not.
3. The protocols should not be limited by the app.

Because we click URL-like string only when we want to open it in another application like browsers. And colon-delimited like `hoge:fuga` should not be clickable because it appears everywhere.

Internationalized URI which is valid and we want to click will rarely appear  on our terminal screen. I prefer to be simple and easy to implement.

Which protocols are clickable is to be decided by end users. There may be people who don't want to click 'file:///' but I want. Fortunately, tym has lua so the behavior can be controlled by users.

**Comment by iTakeshi** [comment]
1. The motivation for dropping raw ipv6 support is there is a difficulty to achieve both of the following points:
    * I want to match URI without protocol using an user-configurable "default" protocol. For example, it'd be useful if we can link the string `192.168.0.1/index.html` to `https://192.168.0.1/index.html` when we set `https` as the default protocol.
    * On the other hand, we probably agree with that we should avoid matching any random string including `:` as raw ipv6 address, like `foo:bar`.
2. Dropping internationalized URI should make the implementation simpler, and it might make it easier to tune the regex to meet our requirements listed in points 1 or 3.
3. I agree with the concept, but I'm not sure it's possible to have user-configurable protocol list. It is because the VTE requires the regex fixed at the compile time. I don't know whether we can set custom URI regex at runtime.

**Comment by endaaman** [comment]
1. Personally, I disagree making strings like `192.168.0.1/index.html` clickable.  Users will not think they are not something obviously openable.  And also I find it difficult to distinguish between bear domain like `github.com` and property accessing like `this.width`.
If implemented, we should add another tag (provided by vte_terminal_match_add_regex()) for URI-like string without protocol

2. Agreed.

3. What I meant was we can restrict URI to open by script like the following.

```lua
tym.set_hook('clicked', function(button, uri)
  if uri then
    if not uri:find('^http') then
      return true
    end
  end
end)
```

**Comment by iTakeshi** [comment]
1. 
    > I find it difficult to distinguish between bear domain like github.com and property accessing like this.width.

    Good point. Now I agree with you to limit the regex to match only URIs with a protocol.
2. Okay, we can drop internationalized URI support.
3. I see. I'd be grateful if you could help me implement such a filter.

I'll see what I can do for these tomorrow.
