### ISSUE TITLE
Void Linux dependencies

### ISSUE THREAD

**Issue by 3Kevi** [endaaman/tym#71]
You've asked about the dependencies on other distributions [here](https://github.com/endaaman/tym#other-distros). These are ones, you need for Void Linux.
#### Void Linux
```
$ sudo xbps-install -S vte3-devel lua-devel
```

**Comment by endaaman** [comment]
You can make and open a PR like that.

**Comment by 3Kevi** [comment]
I have opened [a pull request](https://github.com/endaaman/tym/pull/73). Unfortunately, I am not able to link it to this issue.

**Comment by endaaman** [comment]
Done
