### ISSUE TITLE
add signal hooks

### ISSUE THREAD

**Issue by TorchedSammy** [endaaman/tym#72]
mainly what i mean is hooks for signals like sigusr1 and sigusr2

**Comment by endaaman** [comment]
Do you want `sigusr1` and `sigusr2` rather than dbus signal?

**Comment by TorchedSammy** [comment]
yes, i think that'd be easier

**Comment by TorchedSammy** [comment]
well if it's already used then its fine
maybe a way to define dbus signals like hooks, if you can do that

**Comment by endaaman** [comment]
@TorchedSammy 

I added D-Bus signal/method call supports in HEAD of the master branch. Please see README.md and give me your feedback if you have.

**Comment by TorchedSammy** [comment]
looks good to me in general, but

> If the target window is its own one, it will the value of $TYM_ID and --dest can be omitted. So it is enough like below

this is a bit confusing and should be restructured to:
> If the intended target window is the current, `--dest` can be omitted and the value of $TYM_ID will be used instead. As an example, this is enough:
