### ISSUE TITLE
Line height/padding

### ISSUE THREAD

**Issue by pagankeymaster** [endaaman/tym#77]
Hello, all.

![image](https://user-images.githubusercontent.com/80379926/164469357-653f5ebc-f620-4e09-ab92-09c24890febb.png)

Above is the Xresources patch for st.

![image](https://user-images.githubusercontent.com/80379926/164469803-91832ad1-8c16-4714-9c76-acee16231714.png)

This is the kitty terminal.

I was wondering if something like this is already available for tym? Also, please ask if any additional information is needed!

Thank you :)

**Comment by endaaman** [comment]
Hello @pagankeymaster 

Unfortunately, there is no option for line-height and it might be a bit hard to add the option to tym.

Font rendering is all done by VTE (https://gitlab.gnome.org/GNOME/vte) on tym.  If we can interrupt cairo context used to render the VTE screen, the line height can be modified using `pango_layout_set_spacing()` but no such hook exist(maybe just I don't know it tho).

Or if you really want the behavior, you can modify your font itself.

When such hook is added on VTE  in the future, I will implement the `line-height` option.

**Comment by pagankeymaster** [comment]
No worries! I can wait. I'll subscribe to this issue :)

**Comment by endaaman** [comment]
@pagankeymaster 

Added the properties `cell_height` and `cell_width` on [605bd09](https://github.com/endaaman/tym/commit/605bd09d79a90d8bd74ec6e862a105bd56b6cdae)

```
$ ./src/tym --cell_height 150 --height 20 --width 60`
```

![Screenshot_20220621_143715](https://user-images.githubusercontent.com/2020942/174724121-9b367af4-0124-4811-a53b-219c2eb48271.png)

**Comment by pagankeymaster** [comment]
Work perfectly! Thanks for this.

**Comment by pagankeymaster** [comment]
This can be finally closed.
