### ISSUE TITLE
Can't compile in arch linux via AUR and release compilation :C

### ISSUE THREAD

**Issue by AlphaTechnolog** [endaaman/tym#78]
I can't compile tym in my arch linux:

![neofetch](https://user-images.githubusercontent.com/54639968/164990804-6b412e6d-0c17-41ab-b3e8-0732ab88a5bb.png)

Because the command `sudo make install` throws me the next errors:

![Screenshot from 2022-04-24 14-21-17](https://user-images.githubusercontent.com/54639968/164990796-0a94efcc-31ca-48b1-a2e5-6951440fa824.png)

Used the next commands to compile:

```sh
cd ~/Downloads/tym
tar -xf ./tym.*.tar
cd tym-.*
./configure
sudo make install
```

Tried too using the next aur pkgs: `tym` `tym-git`

> Please help me, i really want to config my terminal using lua :C

**Comment by endaaman** [comment]
@AlphaTechnolog 

What version is your VTE? If you are using `vte3-git` package, reinstall it or try `vte3` package.

**Comment by AlphaTechnolog** [comment]
> @AlphaTechnolog
> 
> What version is your VTE? If you are using `vte3-git` package, reinstall it or try `vte3` package.

Thanks for reply!

Hmm, I think it's likely a problem with dependencies versions (like with vte3 as u said), am not in the PC at this moment. When I go back into the action lmao, I'll try with these options:

- reinstall vte3 as u said
- update the complete system lul

Thanks :3

**Comment by AlphaTechnolog** [comment]
> @AlphaTechnolog
> 
> What version is your VTE? If you are using `vte3-git` package, reinstall it or try `vte3` package.

Thanks for reply!

Hmm, I think it's likely a problem with dependencies versions (like with vte3 as u said), am not in the PC at this moment. When I go back into the action lmao, I'll try with these options:

- reinstall vte3 as u said
- update the complete system lul

Thanks :3

**Comment by AlphaTechnolog** [comment]
Problem solved updating arch linux using `sudo pacman -Syu`
