### ISSUE TITLE
Feature Request: Option to use bright colors for bold fonts

### ISSUE THREAD

**Issue by OliverLew** [endaaman/tym#82]
Has to do with some option like "bold is bright" in vte.

**Comment by endaaman** [comment]
How about setting bright color to  `color_bold`?

**Comment by OliverLew** [comment]
I just tried `color_bold`, but it's not working:
```lua
-- theme.lua
return { color_bold = '#00ff00' }
```
Is that supposed to change how these look, or I am doing it wrong:
```sh
printf "\033[1;31mBold red \033[1;91mBold bright red\033[0m\n"
```
The command above is not affected by the color_bold setting.

As for the "bold is bright" setting, it's prob not a spec or standard. What is does is making the "bold red" look like bright red's color, and the same for color0 to color7.

**Comment by endaaman** [comment]
I didn't know VTE has the prop `'bold_is_bright'`.

I tried adding the config entry for it but I don't know whether it works properly.

```
$ echo -e '███normal███\033[1m███bold███\033[0m'
```

The former part won't be bright.

**Comment by OliverLew** [comment]
Thanks again! It works for me as expected.

As for the example, I am not sure if `color_foreground` (default fg) has a corresponding bright color. I guess it's just bold font tricked you to think it's bright, if you increase the font size enough, they are essentially the same color. Normally, the bright colors applies to `color_0` -> `color_8`, `color_1` -> `color_9`, etc. So should you test with the command I provided above, you know it works when the two parts have the same color.

**Comment by endaaman** [comment]
I tested but it looks like bold part is bright when `bold_is_bright` is disabled. Is this appropriate behavior?

**Comment by OliverLew** [comment]
For me it works (this is my own color scheme):
disable
![Screenshot_2022-06-21_14-28-19](https://user-images.githubusercontent.com/12032219/174731190-85ab6422-01c4-4d8b-a137-7cae8c62600a.png)
enable
![Screenshot_2022-06-21_14-28-05](https://user-images.githubusercontent.com/12032219/174731207-cc4aa8ae-0467-433a-b8eb-e0b701638940.png)

**Comment by endaaman** [comment]
On my environment,

enabled:
![Screenshot_20220621_153742](https://user-images.githubusercontent.com/2020942/174732765-9b98afc3-16f4-4bf0-80ec-5a1b7852c2ab.png)

disabled:
![Screenshot_20220621_153706](https://user-images.githubusercontent.com/2020942/174732771-798d9388-7079-42d1-b22d-faf4e163b903.png)

I guess these should be reversed though..

**Comment by OliverLew** [comment]
That is the intended behavior. Enabling `bold_is_bright` should make "bold" look like "bold and bright", while disabling it will differentiate them.

**Comment by endaaman** [comment]
Aha. That makes sense. Thanks for teaching.

**Comment by OliverLew** [comment]
Pleasure :) I'll close the issue then.
