### ISSUE TITLE
Feature Request: Open uri with ctrl + click

### ISSUE THREAD

**Issue by OliverLew** [endaaman/tym#83]
This is my exact problem: I want to use `ctrl+button1` to open uris, otherwise treat uris as normal text, for example I can select them with cursor. Something like [this from termite](https://github.com/aperezdc/termite/commit/e05b83920fdf7f2d1e813227601c343436325eff).

I tried something like this (and others):
```lua
tym.set_hooks({
    ['clicked'] = function(button, uri)
        if uri and button == 1 then
            if tym.check_mod_state('<Ctrl>') then
                tym.open(uri)
            end
            return true
        end
    end,
})
```

But I can't achieve all these at the same time:
1. only open uri with `ctrl` + `button1`
2. single click will not trigger uri open
3. single click will work (e.g. select text) as usual on all text, including uri

The issue is, if the function doesn't return `true` on single click, the default hook will be triggered and open the uri, but otherwise (return `true`) clicking does absolutely nothing on url including selecting the text.

**Comment by endaaman** [comment]
Your request makes sense. Surely, there is no way to **disable URI opening but work as normal text** , so I fixed the specification.

Please check the diff 4162a328556449a417864a5181c1732e169e44de.

**Comment by OliverLew** [comment]
That works, thanks! I will close this issue then.

P.S. The hook now should be a little different:
```lua
tym.set_hooks({
    ['clicked'] = function(button, uri)
        if button == 1 and uri then
            if tym.check_mod_state('<Ctrl>') then
                tym.open(uri)
                return true
            end
        end
    end,
})
```
