### ISSUE TITLE
Possible for daemon to start without GUI?

### ISSUE THREAD

**Issue by xlucn** [endaaman/tym#94]
This is about the systemd unit file. In my use case, I use `startx` to start the X session. So, `tym-daemon.service` will start after boot and before `startx`.

The issue is then tym daemon errored with 'cannot open display', due to X session not started.

Could the daemon start without a graphical environment?

**Comment by endaaman** [comment]
I figured out the same problem also in a normal DE (I am a SDDM/KDE user.). I could check that if the env value is set `DISPLAY=:0` manually, the service works correctly. But the hotfix should not be the best.

There must be a more elegant and smarter way to do this, but I don't know now.

**Comment by endaaman** [comment]
(In general, instead of systemd, DE's "auto start" or something should be used)

**Comment by xlucn** [comment]
> DE's "auto start"

That seems the better work-around.

Back to my original thought. I am not sure if tym can, since it might be limited by what vte can do, start the daemon without requiring a graphical environment. That's the behavior of `urxvtd`, also quite common for other "daemon" processes.

**Comment by endaaman** [comment]
The option `--daemon` reduces the cost to initilize the GUI footprint. It is reasonable that such process needs `DISPLAY` env.

> since it might be limited by what vte can do

Strictly speaking, limited by GTK rather than VTE.

How are `urxvtd` users solving this problem?

**Comment by xlucn** [comment]
Thanks for the explanation.

> How are urxvtd users solving this problem?

The issue doesn't exist for `urxvt`. In a tty, `urxvtd` can start without problems (and then start `urxvtc` in an X session somewhere else), where `tym --daemon` failed.

Maybe `urxvt` has somehow separated code that requires GUI to be only in client side.

**Comment by js-everts** [comment]
In the case of `startx`.  Adding `tym --daemon &` into your `xinitrc` seems to work.

**Comment by endaaman** [comment]
We have the 2 options.
- add an entry to launch `tym --daemon` on yours DE settings
- start manually on your 'xinitrc'

If you want to use  `tym-daemon.service `, set `DISPLAY=:0` but it is not recommended.
