### ISSUE TITLE
Fonts not working

### ISSUE THREAD

**Issue by luaorigin** [endaaman/tym#99]
I am currently unable to getting various fonts working. So far I tried:
* JetBrains Mono
* Ubuntu Mono
* IBM Plex Mono
* Iosevka
* Cascadia Code

None of these fonts have worked. My `config.lua` file looks like the following
```lua
local tym = require('tym' )
tym.set('font', 'Ubuntu Mono 12')
```
I am running tym version `3.4.0`.
Is there something I am generally missing?

Any help would be greatly appreciated :relaxed:

**Comment by js-everts** [comment]
Are your fonts installed correctly? execute `fc-list "Ubuntu Mono"` to see if they are present.

Also make sure your font is not being overridden in `theme.lua`

**Comment by luaorigin** [comment]
Yes I already double checked that. The output of the fc-list "Ubuntu Mono" command is the following:
```sh
/usr/share/fonts/ubuntu/UbuntuMono-RI.ttf: Ubuntu Mono:style=Italic
/usr/share/fonts/ubuntu/UbuntuMono-R.ttf: Ubuntu Mono:style=Regular
/usr/share/fonts/ubuntu/UbuntuMono-B.ttf: Ubuntu Mono:style=Bold
/usr/share/fonts/ubuntu/UbuntuMono-BI.ttf: Ubuntu Mono:style=Bold Italic
```
Furthermore I made sure that there is  no `theme.lua` in my `~/.config/tym` directory.

**Comment by luaorigin** [comment]
Super sorry about all the hassle. I rebooted my System and then everything worked out :sweat_smile: .
Therefore it was just a fault on my end and I will close the issue :+1:
